import { BackendParams } from './FakeBackend';

export const list = [
  {
    id: 1,
    first_name: 'John',
    last_name: 'Doe',
    employment: { title: 'Software Engineer' },
    subscription: { status: 'active' },
    draggable: true,
  },
  {
    id: 2,
    first_name: 'Jane',
    last_name: 'Smith',
    employment: { title: 'Data Scientist' },
    subscription: { status: 'blocked' },
  },
  {
    id: 3,
    first_name: 'Michael',
    last_name: 'Johnson',
    employment: { title: 'Product Manager' },
    subscription: { status: 'idle' },
  },
  {
    id: 4,
    first_name: 'Emily',
    last_name: 'Brown',
    employment: { title: 'UX Designer' },
    subscription: { status: 'active' },
  },
  {
    id: 5,
    first_name: 'Daniel',
    last_name: 'Williams',
    employment: { title: 'DevOps Engineer' },
    subscription: { status: 'blocked' },
  },
  {
    id: 6,
    first_name: 'Sophia',
    last_name: 'Jones',
    employment: { title: 'QA Engineer' },
    subscription: { status: 'idle' },
  },
  {
    id: 7,
    first_name: 'Matthew',
    last_name: 'Garcia',
    employment: { title: 'Backend Developer' },
    subscription: { status: 'active' },
  },
  {
    id: 8,
    first_name: 'Olivia',
    last_name: 'Martinez',
    employment: { title: 'Frontend Developer' },
    subscription: { status: 'blocked' },
  },
  {
    id: 9,
    first_name: 'Joshua',
    last_name: 'Miller',
    employment: { title: 'System Administrator' },
    subscription: { status: 'idle' },
  },
  {
    id: 10,
    first_name: 'Isabella',
    last_name: 'Davis',
    employment: { title: 'Business Analyst' },
    subscription: { status: 'active' },
  },
  {
    id: 11,
    first_name: 'Jacob',
    last_name: 'Rodriguez',
    employment: { title: 'Scrum Master' },
    subscription: { status: 'blocked' },
  },
  {
    id: 12,
    first_name: 'Mia',
    last_name: 'Martinez',
    employment: { title: 'Technical Writer' },
    subscription: { status: 'idle' },
  },
  {
    id: 13,
    first_name: 'Ethan',
    last_name: 'Hernandez',
    employment: { title: 'Cloud Architect' },
    subscription: { status: 'active' },
  },
  {
    id: 14,
    first_name: 'Ava',
    last_name: 'Moore',
    employment: { title: 'CTO' },
    subscription: { status: 'blocked' },
  },
  {
    id: 15,
    first_name: 'Alexander',
    last_name: 'Taylor',
    employment: { title: 'AI Engineer' },
    subscription: { status: 'idle' },
  },
  {
    id: 16,
    first_name: 'Charlotte',
    last_name: 'Anderson',
    employment: { title: 'Security Analyst' },
    subscription: { status: 'active' },
  },
  {
    id: 17,
    first_name: 'James',
    last_name: 'Thomas',
    employment: { title: 'Database Administrator' },
    subscription: { status: 'blocked' },
  },
  {
    id: 18,
    first_name: 'Amelia',
    last_name: 'Jackson',
    employment: { title: 'Full Stack Developer' },
    subscription: { status: 'idle' },
  },
  {
    id: 19,
    first_name: 'William',
    last_name: 'White',
    employment: { title: 'Solutions Architect' },
    subscription: { status: 'active' },
  },
  {
    id: 20,
    first_name: 'Harper',
    last_name: 'Harris',
    employment: { title: 'Network Engineer' },
    subscription: { status: 'blocked' },
  },
  {
    id: 21,
    first_name: 'David',
    last_name: 'Martin',
    employment: { title: 'Sales Engineer' },
    subscription: { status: 'idle' },
  },
  {
    id: 22,
    first_name: 'Ella',
    last_name: 'Thompson',
    employment: { title: 'Data Engineer' },
    subscription: { status: 'active' },
  },
  {
    id: 23,
    first_name: 'Joseph',
    last_name: 'Garcia',
    employment: { title: 'Software Engineer' },
    subscription: { status: 'blocked' },
  },
  {
    id: 24,
    first_name: 'Abigail',
    last_name: 'Martinez',
    employment: { title: 'Web Developer' },
    subscription: { status: 'idle' },
  },
  {
    id: 25,
    first_name: 'Benjamin',
    last_name: 'Lee',
    employment: { title: 'Data Analyst' },
    subscription: { status: 'active' },
  },
  {
    id: 26,
    first_name: 'Madison',
    last_name: 'Perez',
    employment: { title: 'Project Manager' },
    subscription: { status: 'blocked' },
  },
  {
    id: 27,
    first_name: 'Andrew',
    last_name: 'Gonzalez',
    employment: { title: 'IT Support Specialist' },
    subscription: { status: 'idle' },
  },
  {
    id: 28,
    first_name: 'Grace',
    last_name: 'Wilson',
    employment: { title: 'Machine Learning Engineer' },
    subscription: { status: 'active' },
  },
  {
    id: 29,
    first_name: 'Christopher',
    last_name: 'Anderson',
    employment: { title: 'Software Developer' },
    subscription: { status: 'blocked' },
  },
  {
    id: 30,
    first_name: 'Sofia',
    last_name: 'Thomas',
    employment: { title: 'Cloud Engineer' },
    subscription: { status: 'idle' },
  },
];

// Default parameters for dummy backend requests
export const defaultParams: BackendParams = {
  searchTerm: '',
  sortField: 'first_name',
  sortOrder: 'asc',
  currentPage: 1,
  itemsPerPage: 10,
};
